# Generated by Django 5.0.6 on 2024-05-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
